### ISSUE TITLE
Is the sample Azure Pipeline up-to-date with the scheduled change in kubeconfig?

### ISSUE THREAD

**Issue by KPLauritzen** [dfds/ado-deployment-templates#9]
Hello. 

Could you provide an example (or update the existing example) for an Azure DevOps deployment pipeline? 
Following this announcement: https://dfdsit.statuspage.io/incidents/g4v277v498r0?utm_source=slack I expect that the pipeline has to change. For example, you mention that I should no longer use `aws-iam-authenticator`, but that is still what you use here: https://github.com/dfds/ado-deployment-templates/blob/master/ASP.NET%20Core%20sample/azure-pipelines/azure-pipelines.yaml#L108

**Comment by avnes** [comment]
Thanks for your contribution @KPLauritzen - This is certainly something we need to look into ASAP.

**Comment by avnes** [comment]
I only got it to work if specifying the --region as an option for saml2aws. So I have raised a PR on the pipeline to include that. 
https://github.com/dfds/ado-deployment-templates/pull/10

The same PR also updates both saml2aws and aws-iam-authenticator. 

Please note that Amazon has handed the the tool over to the Kubernetes Special Interest Group. That is why the semantic version number has been "reset".

**Comment by KPLauritzen** [comment]
That is great. I will try it out in the pipeline we discussed

**Comment by avnes** [comment]
PR merged
